# Generated by Django 5.1.7 on 2025-03-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_recipeimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipe_name',
        ),
    ]
