# Generated by Django 5.1.7 on 2025-03-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_rename_name_recipe_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='name',
        ),
    ]
